### ISSUE TITLE
Ignore lambda and layer changes when applying changes

### ISSUE THREAD

**Issue by justinlittman** [LD4P/rdf2marc#103]
Changes to the rdf2marc lambda and layer are pushed to AWS by CircleCI; Terraform is not aware of the changes and should not overwrite the changes.

```
Terraform will perform the following actions:

  # aws_lambda_function.rdf2marc_function will be updated in-place
  ~ resource "aws_lambda_function" "rdf2marc_function" {
        id                             = "sinopia-rdf2marc-development"
      ~ last_modified                  = "2021-09-20T17:38:31.019+0000" -> (known after apply)
      ~ layers                         = [
          - "arn:aws:lambda:us-west-2:418214828013:layer:rdf2marcDeps:22",
          + "arn:aws:lambda:us-west-2:418214828013:layer:rdf2marcDeps:7",
        ]
      ~ source_code_hash               = "88dbEXgqlztz/ShfVCcVgup9A8CXKkdxAirhyBvtEp0=" -> "DuW2tkCYG7dK9nwsVXCLHYj8aX7ibOqUHZSLGVrV3Io="
        tags                           = {}
        # (17 unchanged attributes hidden)

        # (1 unchanged block hidden)
```

Please change the TF configuration so that these changes are ignored.

**Comment by kamchan** [comment]
the aws_lambda_function "rdf2marc_function" is using an optional parameter (layers) to attach to the lambda function.  When that's commented out, it looks like it will remove an older version that it managed (ie version 22 from the terraform plan output)?  but does not add a new layer.    Can we test that in development and see if that is the behavior you expect?  @justinlittman 

https://github.com/sul-dlss/terraform-aws/blob/master/organizations/development/sinopia/sinopia-marc-lambda.tf#L75

**Comment by justinlittman** [comment]
As feared/expected, that removed the layer when applied. However, the layer is necessary.

**Comment by kamchan** [comment]
this is already applied which looks to ignore layer changes.

https://github.com/sul-dlss/terraform-aws/pull/897/files
