### ISSUE TITLE
FAST headings do not convert to MARC

### ISSUE THREAD

**Issue by NancyL** [LD4P/rdf2marc#111]
**Type of change**
Defect

**Example RDF records**
https://api.stage.sinopia.io/resource/3eb5f480-60d6-4732-8daf-02d8d6f26eb7 (Instance)
https://api.stage.sinopia.io/resource/7b03cc32-d121-490e-bae6-8ba51ff8e95a (work)

**Resource template**
Which resource template does this apply to? In which Sinopia environment (development, stage, production)?
stage: pcc:bf2:Monograph:Work/ld4p:RT:bf2:Monograph:Work

**Expected MARC**
What MARC did you expect to receive?
For OCLC FAST topic: 650 #7 Medicine, Medieval $2 fast $0 http://id.worldcat.org/fast/1015277
For OCLC FAST geographic: 651 #7 Germany $2 fast $0 http://id.worldcat.org/fast/1210272
For OCLC FAST event_name 647 #7 World War (1939-1945) $0 http://id.worldcat.org/fast/1180924

**Actual MARC**
What MARC did you actually receive (if mapped incorrectly)?
It did not convert at all. Also Event_name lookup is not working in stage (it does in production) so I can't provide an example in this record

**Expected mapping logic**
Please describe the logic of the mapping.
bf:subject _lookup to various FAST vocabularies_
each vocabulary has a separate MARC field they map to (see above)

This is particularly important because we cannot use LCSH correctly in Sinopia for all headings.

**Comment by justinlittman** [comment]
Not a defect; FAST is not implemented.

**Comment by jcoyne** [comment]
@NancyL We don't support the 647 field yet. Can you write a new ticket for that?
