### ISSUE TITLE
URI & label created in Sinopia do not convert to MARC

### ISSUE THREAD

**Issue by NancyL** [LD4P/rdf2marc#129]
**Type of change**
New mapping

**Example RDF records**
Please provide URIs or RDF of the `bf:Instance`. If providing RDF, Turtle is preferred.

https://api.stage.sinopia.io/resource/1e046a1b-87fe-4eca-b036-08d35dc53579 (and its related bf:Work https://api.stage.sinopia.io/resource/323a3f82-1095-4d0b-96a6-08bc2a511789)

**Resource template**
stage pcc:bf2:Monograph:Instance/pcc:bf2:Monograph:Work
specifically the nested templates bf:Contribution & bf:ProvisionActivity

**Expected MARC**
What MARC did you expect to receive?
050  0 $a G1526.G3 $b K3 2017 
100 1# $a Name, Madeup $0 https://api.stage.sinopia.io/resource/96c11125-b98b-41b0-94bf-dd84b8dfce45
245 00 $a The California field atlas $c written and illustrated by Obi Kaufmann 
250    $a 1st edition 
264  1 $a Berkeley (Calif.) $b Unknown Publisher $c 2017

**Actual MARC**
What MARC did you actually receive (if mapped incorrectly)?
...
050  0 $a G1526.G3 $b K3 2017 
245 00 $a The California field atlas $c written and illustrated by Obi Kaufmann 
250    $a 1st edition 
264  1 $a Berkeley (Calif.) $c 2017 
...

**Expected mapping logic**
Please describe the logic of the mapping.

The two missing elements (a primary contributor and a publisher) are both entities created in Sinopia, with Sinopia URIs and labels. This was necessary because they do not exist in any of our lookups. rdf2marc, however, only converts lookups and there is no lookup to non-work/instance/item entities in Sinopia in the conversion (or so I guess...). But like the lookups, these URIs should map to the MARC field relevant to the nested template they are part of (bflc:PrimaryContribution for the first; bf:ProvisionActivity for the second). 

On the level of Sinopia itself, some sort of lookup of all Sinopia URIs instead of just particular ones would increase the number of entities that will convert to MARC. That might be a first step.

On a bigger scale, this is more than just an issue with Sinopia URIs. I could create a name authority record in the LC file, but I won't get a live URI for the name for several days. We do know, however, the form of the URI, and were hoping we could enter that instead. But again, there would be no lookup available for some time (when we add up the delay in URI creation & the update of the QA lookup). 

When we are creating descriptions for new items, names & very often publishers will not have URIs available through lookups. At the moment we seem stuck with adding these in by hand to the MARC record.

**Comment by michelleif** [comment]
in progress via 2 smaller tix

**Comment by justinlittman** [comment]
This now produces:
```
100 1  $a Name, Madeup $e Author $0 https://api.stage.sinopia.io/resource/96c11125-b98b-41b0-94bf-dd84b8dfce45
245 10 $a The California field atlas $c written and illustrated by Obi Kaufmann
250    $a 1st edition
264  1 $a Berkeley (Calif.) $b Unknown Publisher $c 2017
```
