### ISSUE TITLE
Fallback when resolving models

### ISSUE THREAD

**Issue by justinlittman** [LD4P/rdf2marc#131]
Currently, resolving with `Resolver.resolveModel()` is only supported for certain authorities; when an authority is not supported, the data is dropped.

This strategy should be changed such that:
* If a literal is provided, the literal is used for the appropriate model field.
* If a URI is URI, the literal is used for the appropriate model field.
* If a label for the URI is provided and the label is different than the URI, the label is used for the appropriate model field.

The following describes the appropriate fields for different models:
* Corporate name: corporate_name for literal/label; authority_record_control_numbers for URI.
* Genre form: genre_form_data for literal/label; authority_record_control_numbers for URI.
* Geographic name: geographic_name for literal/label; authority_record_control_numbers for URI.
* Meeting name: meeting_name for literal/label; authority_record_control_numbers for URI.
* Personal name: personal_name for literal/label; authority_record_control_numbers for URI.
* Topical term: topical_term_or_geo_name for literal/label; authority_record_control_numbers for URI.

**Comment by justinlittman** [comment]
If the object for the property is a literal (i.e., the thing that is being resolved).

For example, in https://github.com/LD4P/sinopia_editor/blob/main/src/components/App.jsx#L195-L207, the literal case is handled; the fallback for URI/label would need to be added.

**Comment by jcoyne** [comment]
I guess my problem understanding this ticket is that `Resolver.resolveModel()` never gets a literal, it always takes a URI.

**Comment by justinlittman** [comment]
Correct. That should not change.
________________________________

**Comment by jcoyne** [comment]
@justinlittman So... "If a literal is provided, the literal is used for the appropriate model field.".... brings me back to " providing a literal to what, if not to `Resolver.resolveModel()`?

**Comment by justinlittman** [comment]
If the object of the triple is a literal instead of a URI, use the literal for the model field instead of resolving to get a label.
________________________________

**Comment by jcoyne** [comment]
But `Resolver.resolveModel()` just gets a URI, not a triple.

**Comment by justinlittman** [comment]
For example, https://github.com/LD4P/rdf2marc/blob/f8b7fb42d9d36f509f90abcae76881fa07c038c4/lib/rdf2marc/rdf2model/mappers/added_entry_fields.rb#L54-L58:
```
def added_entry_name_with_roles(contrib_term, role_uris, key_symbol, model_class)
          result = if contrib_term.is_a?(RDF::Literal)
                     { thesaurus: 'not_specified', key_symbol => contrib_term.value }
                   else
                     Resolver.resolve_model(contrib_term&.value, model_class)
                   end
          result[:relator_terms] = relator_terms(role_uris) if result && relator_terms(role_uris).present?
          result
        end
```

Great -- this already handles literals already, so only support for unresolved URIs need to be handled.
def added_entry_name_with_roles(contrib_term, role_uris, key_symbol, model_class)
          result = if contrib_term.is_a?(RDF::Literal)
                     { thesaurus: 'not_specified', key_symbol => contrib_term.value }
                   else // THIS IS A URI
                      // IF IT CAN BE RESOLVED
                        Resolver.resolve_model(contrib_term&.value, model_class)
                      // ELSE (IT CANNOT BE RESOLVED)
                        // IT DEPENDS ON THE MODEL. HOWEVER, THE APPROACH USED FOR LITERALS WORK.
                        { thesaurus: 'not_specified', key_symbol => THE LABEL (IF PRESENT AND DIFFERENT FROM URI),  authority_record_control_numbers: [contrib_term.value <-- THE URI]}
                   end
          result[:relator_terms] = relator_terms(role_uris) if result && relator_terms(role_uris).present?
          result
        end
```

**Comment by jcoyne** [comment]
So it's the code that invokes `Resolver.resolveModel()`, not `Resolver.resolveModel()` itself that ought to be changed? That wasn't clear to me from the description.

**Comment by justinlittman** [comment]
Yes. Sorry that you couldn't figure out what was in my head ...

**Comment by jcoyne** [comment]
@justinlittman I don't think we have a label for the last case in the class you mentioned.   It might be helpful here if we had sample rdf, because I'm still having a terrible time understanding what is being asked.

**Comment by jcoyne** [comment]
Do we want this refactoring to handle where the subject terms are resolved too?   If so, what should the `key_symbol` be in the case where it's a "topic"?

**Comment by justinlittman** [comment]
Yes. I assume you're talking about https://github.com/LD4P/rdf2marc/blob/f8b7fb42d9d36f509f90abcae76881fa07c038c4/lib/rdf2marc/rdf2model/mappers/subject_access_fields.rb#L41-L43

When, for a topic, there is a URI and a label and the URI can't resolved, then the model would be:
```
{
   topical_term_or_geo_name: <label>,
   authority_record_control_numbers: <URI>
}
```
