### ISSUE TITLE
Fallback when resolving label

### ISSUE THREAD

**Issue by justinlittman** [LD4P/rdf2marc#132]
When resolving a label (`Resolver.resolve_label()`):
* If a literal is provided, use the literal as the label.
* If a URI is provided, but the URI is for an authority that cannot be resolved, and a label is provided for the URI and the label is different than the URI, use the label as the label.

**Comment by justinlittman** [comment]
If the object of the statement is a literal.

For example, for https://github.com/LD4P/rdf2marc/blob/7aaf57e709e48515a95dab8f3be625e85a0b3a34/lib/rdf2marc/rdf2model/mappers/edition_imprint_fields.rb#L49 the literal case is handled; support for using the URI label needs to be added.

**Comment by jcoyne** [comment]
I'm still confused, currently the `Resolver.resolve_label()` method takes a URI.  Are you saying we should allow it to take a literal?

**Comment by justinlittman** [comment]
No. I'm saying that when a literal is provided, the literal should be used as the label (i.e., resolving should NOT be performed).

If a URI and label is provided, but the URI is for an authority that cannot be resolved (i.e., anything other than id.loc.gov or fast), then the label should be used as the label.

**Comment by jcoyne** [comment]
@justinlittman are you saying, refactor the method to take both a graph and a URI. Then check to see if there is a label in the graph for the URI, otherwise resolve the URI and find a label?

**Comment by justinlittman** [comment]
I'd suggest leaving `Resolver.resolve_label()` as is, but refactor any mapper code that calls it. (If this ends not being very DRY, then might need some sort of a helper, but I wouldn't put it in Resolver.)

**Comment by peetucket** [comment]
Am I on the right track here?  https://github.com/LD4P/rdf2marc/pull/134

Also I don't quite understand this: "If a URI is provided, but the URI is for an authority that cannot be resolved, and a label is provided for the URI and the label is different than the URI, use the label as the label."  How can you provide both a URI and a label into the `resolve_label` method?

**Comment by peetucket** [comment]
See https://github.com/LD4P/rdf2marc/pull/147

**Comment by mjgiarlo** [comment]
@justinlittman I hate for this issue to become a revolving door, but I'm not sure I get this one either. Here's the bit I'm unsure about:

> ... a label is provided for the URI 

How/where is the label provided for the URI? Is there sample data or a test that can shed more light on this?

**Comment by justinlittman** [comment]
See @jcoyne's PR for related work: https://github.com/LD4P/rdf2marc/pull/147

The label is provided as an RDFS:label. See this example: https://github.com/LD4P/rdf2marc/issues/131#issuecomment-961200409
