### ISSUE TITLE
RDA 336/7/8 fields $b not $c

### ISSUE THREAD

**Issue by kirkhess** [LD4P/rdf2marc#136]
https://github.com/LD4P/rdf2marc/blob/9a1844b69a07aaea82d7a262eeaacb7f0d25c78b/spec/rdf2marc/model2marc/field_336_spec.rb#L24

https://github.com/LD4P/rdf2marc/blob/3f7e605028ec0c6227d514b4f96271879410f042/spec/rdf2marc/model2marc/field_337_spec.rb#L24

https://github.com/LD4P/rdf2marc/blob/3f7e605028ec0c6227d514b4f96271879410f042/spec/rdf2marc/model2marc/field_338_spec.rb#L24

The code subfield is $b not $c.

**Comment by NancyL** [comment]
Yes, this is correct. They all should be $b
