### ISSUE TITLE
003 Control Number Identifier

### ISSUE THREAD

**Issue by kirkhess** [LD4P/rdf2marc#137]
https://github.com/LD4P/rdf2marc/blob/6eb7c40acaebf2a2920281e0f5a834eea1e141d2/lib/rdf2marc/model2marc/record.rb#L16

This is the organization code (either MARC or OCLC) whose control number is contained in the 001, i.e. ocolc, or dlc. 

It shouldn't be a uri - for the standpoint of the converter it sort of makes sense to have a default option as a env variable.

LC maps the 003 to a bf:Work or bf:Instance bf:adminMetadata/bf:AdminMetadata/bf:assigner/bf:Assigner/bf:code literal value.

**Comment by michelleif** [comment]
@NancyL how do you want the organization code converted to MARC now that it's a URI in the template?

**Comment by michelleif** [comment]
@NancyL please advise

**Comment by NancyL** [comment]
I think this is a question for @vitustang

**Comment by vitustang** [comment]
My feeling is that the converter should not assign an 003. The MARC record will be loaded into a ILS (and different ILSs depending on who is initiating the export). If this MARC record is exchanged with another system, then it would be exported from that ILS, and on export that ILS will put the record id in the 001 and the organization code in the 003. So, I see no reason for the converter to pre-supply that code. It could be tricky for it to provide the correct code. For example, for Stanford University, we have these different MARC organization codes:

- SUL = CSt

- Law = CSt-Law

- Business = CSt-Bu

- Lane Medical = CSt-L

- Hoover Institution = CSt-H

The converter would not know which is the right code based on the user's Sinopia account, I think, unless you ask them for this sort of affiliation info.

**Comment by michelleif** [comment]
so do we want to stop creating the 003 in rdf2marc conversion?

**Comment by kirkhess** [comment]
In [bibframe2marc](https://github.com/lcnetdev/bibframe2marc) the specs have the mapping for 003 to:
adminMetadata/AdminMetadata/identifiedBy/Local/assigner/Agent/code
And that bf:Local would have the identifier value which goes in the 001. There's no 001 assigned by this service as far as I can tell so that's another reason not to use the 003.  

For a valid 'operational' marc record you'll want a 001/003 - if you don't put it in a bf:Local you could generate it on the fly w/ a default code (CSt). The LC stylesheet also has an option to default the assigner code, that was why I suggested it. 

This service is using the bf:source as as substitute for the bf:assigner, which should be a MARC org code not a id.loc.gov rwo and should do something if it isn't a marc org code url (default/blank/exception...) this is also a problem in the 040$a $c and $d

**Comment by michelleif** [comment]
@NancyL please advise on whether there is Sinopia work that needs to be done here

**Comment by NancyL** [comment]
I believe Vitus says no there is not, but best to ask him @vitustang

**Comment by michelleif** [comment]
@kirkhess what is the problem in Sinopia that needs to be fixed?

**Comment by michelleif** [comment]
@kirkhess never mind, we decided to stop creating an 003

**Comment by michelleif** [comment]
so the development work is: stop mapping 003

**Comment by justinlittman** [comment]
Please remove the rdf to model mapping for `control_number_id`: https://github.com/LD4P/rdf2marc/blob/6eb7c40acaebf2a2920281e0f5a834eea1e141d2/lib/rdf2marc/rdf2model/mappers/control_fields.rb#L10
