### ISSUE TITLE
Wrong first indicator mapping bf:Distribution to MARC 264

### ISSUE THREAD

**Issue by NancyL** [LD4P/rdf2marc#148]
**Type of change**
Change to an existing mapping

**Example RDF records**
https://api.development.sinopia.io/resource/466e610d-1213-4936-9e11-aa0447371ab1

**Resource template**
development: stanford:pcc:bf2:Monograph:Instance

**Expected MARC**
245 10 $a A new introduction to bibliography $c by Philip Gaskell 
264  1 $a New Castle (Del.) $b Oak Knoll Press 
264  1 $a Winchester (England) $b St. Paul's bibliographies $c 1995 
**264  2 $a New York (N.Y.) $b Lyons & Burford, Publishers** 
264  3 $a London (England) $b Random Brothers 

**Actual MARC**
245 10 $a A new introduction to bibliography $c by Philip Gaskell 
264  1 $a Winchester (England) $b St. Paul's bibliographies $c 1995 
264  1 $a New Castle (Del.) $b Oak Knoll Press 
264  3 $a New York (N.Y.) $b Lyons & Burford, Publishers

**Expected mapping logic**
The first 2 264s are correct in that they map from bf:provisionActivity/bf:Publication = 264 2nd indicator "1"
The 3rd 264 maps from bf:provisionActivity/bf:Distribution = 264 2nd indicator "2" (this is what needs fixing!)
The 4th 264 maps from bf:provisionActivity/bf:Manufacture = 264 2nd indicator "3"

**Comment by NancyL** [comment]
yup, that's what I have as "actual MARC". The top is what is expected.

**Comment by NancyL** [comment]
oops, I see I said first indicator, when it should be second indicator. Did I mess this up?

**Comment by mjgiarlo** [comment]
@NancyL now that this fix is in, do you want to run it against the test record and verify?

**Comment by NancyL** [comment]
@mjgiarlo looks good, despite my dumb error! Thanks!

**Comment by mjgiarlo** [comment]
@NancyL No worries. Thanks for writing up the issue with the expected/actual data in it. Made it very easy to put in a fix.
