### ISSUE TITLE
Map bf:provisionActivityStatement to MARC 500 field

### ISSUE THREAD

**Issue by NancyL** [LD4P/rdf2marc#156]
**Type of change**
New mapping

**Example RDF records**
Please provide URIs or RDF of the `bf:Instance`. If providing RDF, Turtle is preferred.

https://api.stage.sinopia.io/resource/3eb5f480-60d6-4732-8daf-02d8d6f26eb7 (Physica)
![image](https://user-images.githubusercontent.com/5078198/144918315-7b5fbc6d-0845-454b-b525-640e168708b9.png)

**Resource template**
Which resource template does this apply to? In which Sinopia environment (development, stage, production)?
pcc:bf2:Monograph:Instance on stage & dev

**Expected MARC**
What MARC did you want to receive?

500 ## $i Transcribed publication statement: $a Rochester, Vermont : Healing Arts Press, [1998]

**Expected mapping logic**
bf:provisionActivityStatment literal to map to a generic 500
if possible, add the $i Transcribed publication statement: before the $a in the field.

This request is to temporarily assist in mitigating an issue we have with the conversion results for provision activity. It really should show the transcribed version, but it is difficult to parse, does not allow for showing publication vs distribution vs manufacture, and we need the coding from the current conversion to populate the 008 country code. So, adding this into the conversion (hopefully in a simple fashion) will allow a cataloger to adjust the record if necessary with the data brought through.

**Comment by ndushay** [comment]
Is it concerning that https://www.loc.gov/marc/bibliographic/bd500.html shows no subfield i ?   (I was trying to figure out what to call subfield i)

**Comment by justinlittman** [comment]
@NancyL ?

**Comment by NancyL** [comment]
@ndushay wow, sorry about that. So instead, could we do:

500 ## $a Transcribed publication statement: Rochester, Vermont : Healing Arts Press, [1998]

This would mean just adding the set text in front of the statement from Sinopia
