### ISSUE TITLE
Map bflc:TransliteratedTitle to 246

### ISSUE THREAD

**Issue by NancyL** [LD4P/rdf2marc#160]
**Type of change**
New mapping

**Example RDF records**
Please provide URIs or RDF of the `bf:Instance`. If providing RDF, Turtle is preferred.

https://stage.sinopia.io/editor/resource/1cca2add-33c9-4fbc-a430-b133d0c7bb88

**Resource template**
Which resource template does this apply to? In which Sinopia environment (development, stage, production)?

Stanford:bf2:Monograph:Instance on Stage

**Expected MARC**
What MARC do you expect to receive?

245 10 $a أبحث عن ليلى : $b روايه
246 1# $i Transliterated title: $a Abḥathu ‘an Laylá : $b riwāyah

**Expected mapping logic**
I would like to get the transliterated version of the title in the MARC record. The simplest way to do this right now is to take bf:title/bflc:TransliteratedTitle and put it in a 246 field
So
bf:title [a bflc:TransliteratedTitle ;  
bf:mainTitle ;  
bf:subtitle ;
bf:partNumber ;
bf:partName 
] .

maps to the 246 as follows:

246 1# $i Transliterated title: $a mainTitle $b subtitle $npartNumber $p partName

**Comment by ndushay** [comment]
uri of example appears to be https://api.stage.sinopia.io/resource/1cca2add-33c9-4fbc-a430-b133d0c7bb88

**Comment by NancyL** [comment]
yes, as given above. Is there a problem with the example?

**Comment by ndushay** [comment]
@NancyL Questions:

1.  I'm assuming translated title statements are NOT the same as transliterated title statements and should not be treated the same.  True?  (looks like translated titles go in Marc 242)
2. I'm assuming we are deliberately not considering transliterated titles to be parallel titles.  True?
3. currently, it looks like translated titles do NOT map the subtitle.  Should they?
4. currently, it looks like all forms of variant titles (meaning those that map to 246) do NOT map the subtitle.  Should they?
5. 4. currently, it looks like former titles (which map to Marc 247) do NOT map the subtitle.  Should they?

**Comment by NancyL** [comment]
1. There is no longer a "translated title", only "transliterated title" which is what that was supposed to be. The 242 is not generally used & LC has been pushing it. You could use that instead, but I suspect it does not appear in SearchWorks. My use of the 246 was intended as a stop gap. But if it does map into SW, we could use that, but with "Transliterated" not "translated". 
2. No they aren't since it is the same language, just a different script. In my ideal world they would simply be an alternate label to the script, but alas no.
3. they should
4. Usually they are not added to a 246. If deemed important, they get their own 246, so no. Because this one is a transliteration, I included everything.
5. checking to see if we even use it.
6. Hmm, it's what is always done, but if it's better to leave out, since the rest of the punctuation is left out, that would be okay (or use the 242 I guess)

**Comment by NancyL** [comment]
Expected mapping logic
I would like to get the transliterated version of the title in the MARC record. The simplest way to do this right now is to take bf:title/bflc:TransliteratedTitle and put it in a 242 field
So
bf:title [a bflc:TransliteratedTitle ;
bf:mainTitle ;
bf:subtitle ;
bf:partNumber ;
bf:partName
] .

maps to the 242 as follows:

242 10 $a mainTitle $b subtitle $npartNumber $p partName

**Comment by ndushay** [comment]
More:
1.  242 *is* indexed in SearchWorks, and already is spoken for;  our test code has an example like this:
```   <#{instance_term}> <http://id.loc.gov/ontologies/bibframe/title> _:b41.
        _:b41 a <http://id.loc.gov/ontologies/bibframe/VariantTitle>;
          <http://id.loc.gov/ontologies/bibframe/mainTitle> "World of art"@eng;
          <http://id.loc.gov/ontologies/bibframe/partName> "Selected Internet resources"@eng, "Student handbook"@eng;
          <http://id.loc.gov/ontologies/bibframe/variantType> "translated"@eng, "acronym"@eng.
```

6.  I can include the colon.  
It's up to you if you want to use 246 or 242.  Does `@ar-Latn-t-ar-m0-alaloc` have a 3 letter marc language code to go in 242y ?

3.  I will make existing code for translated titles map the subtitle.
4.  If we stick with 246 for transliterated title, I'm hearing you would like transliterated titles to have subtitle if present, but other forms of variant titles in 246 should _not_ have subtite mapped.

**Comment by NancyL** [comment]
bf:VariantTitle should not be mapped to a 242. It should be mapped to a 246 3#. Only a bflc:TransliteratedTitle should map to the 242

**Comment by ndushay** [comment]
For 242y -- ignore that -- we're not currently mapping to it for translated titles.

**Comment by ndushay** [comment]
Speaking in realtime with Nancy:

A.  our current code to create "translated_title" that eventually maps to Marc 242 ... may be no longer needed.  Nancy will investigate.

**Comment by NancyL** [comment]
After testing, I see that the 242 does indeed display in SearchWorks. So... bflc:TransliteratedTitle should map to the 242. bflc:TransliteratedTitle replaced bflc:TranslatedTitle; there is no longer a bflc:TranslatedTitle. What is in the conversion specs needs to be updated. So it is fine to get rid of the conversion specs for translated title and replace it with bflc:TransliteratedTitle.
