### ISSUE TITLE
MARC conversion--Not adding author with literal and no URI

### ISSUE THREAD

**Issue by RobertRohr** [LD4P/rdf2marc#170]
The MARC conversion is not creating a 1XX field for the primary contributor when the primary contributor is only entered as a literal with no corresponding URI. For example, see the following work resource: https://api.stage.sinopia.io/resource/f0f8a70a-74f5-44f2-9096-c50c81233e7b. The author is there as a literal, but does not end up in the converted MARC record. I'm attaching screen shots of the work instance with the author, the section of the RDF preview with the author's name in the RDF, and of the converted MARC record.
![Creator as literal](https://user-images.githubusercontent.com/48070028/146080891-44995a3b-c222-4a47-9d6b-031296592912.PNG)
![RDF with author as literal](https://user-images.githubusercontent.com/48070028/146080899-15c2a94b-bc4f-48c7-9bb5-4f5361a06a49.PNG)
![Record with missing 100](https://user-images.githubusercontent.com/48070028/146080920-1ccafa96-a6a5-4a11-a066-2849d19a37ec.PNG)

**Comment by RobertRohr** [comment]
For things like contributor, I think we would want to convert the data to MARC 1XX or 7XX regardless of whether there is a URI or not, especially since quite often the agent we want to add to a bibliographic description is not in QA and we have to enter a literal.

**Comment by NancyL** [comment]
In our discussion with Justin, we agreed that any label in converted fields would convert over to MARC.

**Comment by michelleif** [comment]
yes that's right, sorry about that. I will fix the documentation and let's get this fixed. I will see who is available to fix.
