### ISSUE TITLE
form of work: an incorrect second indicator (“0” instead of correct “7”) 

### ISSUE THREAD

**Issue by jimfhahn** [LD4P/rdf2marc#187]
**Type of change**
change to existing mapping

**Example RDF records**
Please provide URIs or RDF of the `bf:Instance`. If providing RDF, Turtle is preferred.

https://api.stage.sinopia.io/resource/70904243-8e7e-4bca-9e41-9db38f640b69

**Resource template**
Which resource template does this apply to? In which Sinopia environment (development, stage, production)?

PCC Work Template in stage.

**Expected MARC**
What MARC did you expect to receive?

655  7 $a Handbooks and manuals $0 http://id.loc.gov/authorities/genreForms/gf2014026109 $2 lcgft 

**Actual MARC**
What MARC did you actually receive (if mapped incorrectly)?

655  0 $a Handbooks and manuals $0 http://id.loc.gov/authorities/genreForms/gf2014026109 $2 lcgft 

**Expected mapping logic**
Please describe the logic of the mapping.

transferred nicely into a 655 with $2 lcgft, but had an incorrect second indicator (“0” instead of correct “7”)

**Comment by NancyL** [comment]
Agree! This needs to be fixed!
