### ISSUE TITLE
MARC conversion on DVD template-- complex subject problem

### ISSUE THREAD

**Issue by gdegroat** [LD4P/rdf2marc#24]
In Sinopia Stage, using Firefox in DVD unnested templates for instance and work:

The MARC conversion worked mostly (i assume special mappings haven't been done yet for this template), however, i think that one of the subject headings should have appeared in the MARC conversion, but didn't.  In the Work template, the third subject, Actresses--Drama, did match with a URI from id.loc.gov, so i think it should have converted to MARC.  My understanding is that the literals are being ignored but this one was not a literal.

![image](https://user-images.githubusercontent.com/44270367/95915727-7372fc80-0d5c-11eb-97b3-9493cb8d8648.png)

**Comment by justinlittman** [comment]
FYI @gdegroat -- This fix has been deployed to stage.
