### ISSUE TITLE
Fix failing lambda builds

### ISSUE THREAD

**Issue by mjgiarlo** [LD4P/rdf2marc#299]
Lambda builds on changes to `main` have been failing for a number of weeks in CI, *e.g.*, https://app.circleci.com/pipelines/github/LD4P/rdf2marc/667/workflows/365d7a5f-f29f-4b03-b624-0968d07d5501/jobs/2578

The apparent problem is lack of support for Ruby 2.7, which was end-of-lifed in March 2023. There are a few spots in the `rdf2marc` codebase that reference this version of Ruby, apparently all because this is what's specified in Terraform. You may want to consult with Jeremy and/or Ops, but here's what will need to change to update the version of Ruby (3.2.2 is the latest stable version, and what we're using across the board now):

* https://github.com/sul-dlss/terraform-aws/blob/main/organizations/production/sinopia/sinopia-marc-lambda.tf#L57-L79
* https://github.com/LD4P/rdf2marc/blob/main/.circleci/config.yml#L105-L113
* https://github.com/LD4P/rdf2marc/blob/main/README.md?plain=1#L19-L20
* https://github.com/LD4P/rdf2marc/blob/main/lambda-s3/README.md?plain=1#L14-L19

**Comment by justinlittman** [comment]
Fixed.
