### ISSUE TITLE
Consider 050$b from item record

### ISSUE THREAD

**Issue by justinlittman** [LD4P/rdf2marc#32]
From #30 (@jimfhahn):

> Another related question we had was 050 indicator "b" will there be a plan to pull in item level data for $b - Item number (NR) as described here: https://www.loc.gov/marc/bibliographic/bd050.html or will the MARC converter mainly be concerned with Work/Instance conversion not necessarily looking at the item?

**Comment by justinlittman** [comment]
@NancyL @vitustang Can you determine if/ what needs to be done for this ticket? Thanks!

**Comment by vitustang** [comment]
@justinlittman this is the first time I see this ticket, so I'm not familiar with the history or context of the question, but I'll take a stab at answering.
The _Monograph Work (BF2) Un-Nested template has a place for inputting a "Library of Congress Classification", with two subunits: "LC classification number" and "Classification item number". These two are the equivalent of MARC 050 $a and $b.
So, the 050 $b item number is not related to the Sinopia item record. The term "item" used in the MARC definition is more like "manifestation" in the FRBR/LRM model, and not like the Bibframe "item".
So, if the rdf2marc converter is going to create a 050 field in the MARC record, both the $a and $b of that field would come from the Sinopia "work" record. The converter does not have to look for the 050 $b in the Sinopia "item" record.
Let me know if this does not answer the question.

**Comment by justinlittman** [comment]
We are currently mapping from the Work (see https://github.com/LD4P/rdf2marc/blob/main/lib/rdf2marc/rdf2model/mappers/number_and_code_fields.rb#L113), so I am going to close this ticket.
