### ISSUE TITLE
Add 758 field with BF work URI to converted MARC data

### ISSUE THREAD

**Issue by NancyL** [LD4P/rdf2marc#34]
When converting, add a 758 field to the MARC record, as follows:

758 ## $4 http://id.loc.gov/ontologies/bibframe/instanceOf $e Instance of: $a [bf:Work bf:mainTitle] $1 [URI of bf:Work]

This provides a strong link between the MARC and the BF.

**Comment by justinlittman** [comment]
@NancyL Can you provide an example? It will help make sure this is implemented correctly.

**Comment by NancyL** [comment]
245 10 $a Linked data for libraries, archives and museums :$b how to clean, link and publish your metadata /$c Seth van Hooland and Ruben Verborgh.
758 ## $4 http://bibframe.org/vocab/instanceOf  $i Instance of: $a Linked data for libraries, archives and museums $0 http://worldcat.org/entity/work/id/1840249565

**Comment by jcoyne** [comment]
@NancyL would it actually look like this?
```
758    $4 http://id.loc.gov/ontologies/bibframe/instanceOf $e Instance of: $a Hildegard von Bingen's Physica $1 https://api.stage.sinopia.io/resource/3eb5f480-60d6-4732-8daf-02d8d6f26eb7
```

this uses the title statement rather than the variant titles.

**Comment by NancyL** [comment]
Actually, it should look like this:

758 ## $4 http://bibframe.org/vocab/instanceOf $i Instance of: $a Physica. English $0 https://api.stage.sinopia.io/resource/7b03cc32-d121-490e-bae6-8ba51ff8e95a

It should be the bf:mainTitle of the bf:Work, not the bf:Instance (we are saying the bib record is an instance of the work)
