### ISSUE TITLE
Assigned 245 first indicator "1" without 1XX

### ISSUE THREAD

**Issue by takamarut** [LD4P/rdf2marc#35]
MARC conversion assigned 245 first indicator "1" without 100.
Stage instance URI: https://api.stage.sinopia.io/resource/0ae18317-2909-4343-a29e-bdb8e5e7aba8
Title: Interdisziplinäre S3-Leitlinie für die Früherkennung, Diagnostik, Therapie und Nachsorge des Mammakarzinoms

![245and246](https://user-images.githubusercontent.com/50535652/100012271-00b86080-2da1-11eb-9136-266a0438707c.PNG)

**Comment by justinlittman** [comment]
@takamarut What is the expected result?

**Comment by takamarut** [comment]
The first indicator should be "0" if there is no 1XX.
245 00 ....

**Comment by jcoyne** [comment]
Currently the logic for the 245 first indicator is governed by whether it's an "added" or "no_added". https://github.com/LD4P/rdf2marc/blob/main/lib/rdf2marc/model2marc/field_245.rb#L12

Should we discard that approach?

**Comment by NancyL** [comment]
This is now working correctly for both the 245 with a 1XX and the 245 without a 1XX!
