### ISSUE TITLE
Created two 264 fields for two publisher names and publication places

### ISSUE THREAD

**Issue by takamarut** [LD4P/rdf2marc#36]
MARC conversion created two 264 fields for two publisher names and publication places.
Instance URI: https://api.stage.sinopia.io/resource/0ae18317-2909-4343-a29e-bdb8e5e7aba8
Title: Interdisziplinäre S3-Leitlinie für die Früherkennung, Diagnostik, Therapie und Nachsorge des Mammakarzinoms

![264](https://user-images.githubusercontent.com/50535652/100012681-a5d33900-2da1-11eb-9c72-0f8d902dee9b.PNG)

**Comment by justinlittman** [comment]
@takamarut What is the expected result?

**Comment by takamarut** [comment]
If there are two publishers or issuing bodies on title page of book,
For example: title is published or issued by American Psychiatric Society in Washington, DC and Johns Hopkins University Press in Baltimore, MD 
264 _1 Washington, DC : $b American Psychiatric Society ; $a Baltimore, MD : $b Johns Hopkins University Press, $c 2020.
For example: title is published or issued by AABB in Bethesda, MD and National Institute of Health in Bethesda MD
264_1 Bethesda, MD : $b AABB : $b National Institute of Health, $c 2020.

**Comment by jcoyne** [comment]
![Screen Shot 2021-09-09 at 2.27.23 PM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/fd8ac36a-62b1-40ca-bb24-e308364a12d0)

**Comment by justinlittman** [comment]
@takamarut In the template, Publication is repeatable and then within that, Place, Name, and Date are repeatable. Our current logic is to create a 264 for each Publication, with each Place, Name, and Date as repeatable subfields.

Do you have a different logic to suggest that accounts for the repeatability of the Publication, Place, Name, and Date?

**Comment by NancyL** [comment]
This seems to be repeating the template rather than repeating within each field. If I enter two places in the place field, it does convert to $a place $a place as it should. The conversion of the $b has disappeared at the moment so I can't see what happens there

**Comment by NancyL** [comment]
Repeating the whole template will create 2 264 _1 fields in MARC. In MARC, this is not incorrect; it is incorrect according to cataloging rules, which specify that it goes in one field. If I instead add the second place of publication and publisher in the same template as the first like this:
![image](https://user-images.githubusercontent.com/5078198/134749043-831bfc77-981a-44e4-8594-580029b92790.png)
I get as conversion:
264  1 $a London (England) $a Berkeley (Calif.) $b Macmillan London $b Heyday Books $c 1998 

It should be:
264 _1 $a London (England) $b Macmillan (London) $a Berkeley (Calif.) $b Heyday Books $c 1998

This is complicated I suspect.

And oddly, when I added a second place of publication using GeoNames rather than LC NAF, the GeoNames name did not convert.

**Comment by michelleif** [comment]
@NancyL 
1) we don't convert GeoNames only LCNAF
2) can you create a new ticket that follows the mapping issue template, summarizing what you need changed? i.e., just the info in your last comment about doing $a $b $a $b vs $a $a $b $b

**Comment by NancyL** [comment]
So that basically means we cannot use GeoNames, since that field initiates the creation of the MARC country code in the 008, which is required. Not so bad, because I was beginning to think that it was not a great place to use GeoNames, but does increase restrictions again.

I will do the new ticket

**Comment by NancyL** [comment]
Actually, on second thought, I don't think it is really possible to do this change. It requires the combination of the labels of 2 separate properties be combined in specific ways and we already know from other fields (e.g., extent) that we don't have a good way to do this right now.

**Comment by michelleif** [comment]
do you want to close this ticket then @NancyL ?

**Comment by NancyL** [comment]
So I did not create this ticket in the first place. It is a valid problem; I just have no idea how to solve it.
