### ISSUE TITLE
Converting subjects to MARC from Work?

### ISSUE THREAD

**Issue by jyssy** [LD4P/rdf2marc#37]
Using the internal sinopia converter, regarding this [instance](https://api.stage.sinopia.io/resource/d7adfa65-078f-4b9b-8d12-bd419cf75de2), which has a relationship to this [work](https://api.stage.sinopia.io/resource/ac03096d-822d-48c1-bc66-e25e29b8b3c1), HOLY WAR, this Work has a single subject added, in this case, in FAST, and which has been added with a URI, but does not convert to the MARC file. What would it take to convert subjects to the MARC? Or would LCSH subjects convert, even though FAST subjects do not? The MARC record was perfectly fine I think generally, but am trying to understand subject conversion in the process since this FAST subject did not convert to the MARC. Thank you
![image](https://user-images.githubusercontent.com/30397506/100759623-72526900-33b6-11eb-80c0-e98b2fab020c.png)

**Comment by NancyL** [comment]
Subjects were not included in the initial conversion file. We were not, in this work cycle, intending to create a full MARC record, but an "operational" record for internal use in an ILS.
