### ISSUE TITLE
External Conversion, not getting a validated MARC file

### ISSUE THREAD

**Issue by jyssy** [LD4P/rdf2marc#38]
When using the Converter built within, we request conversion, and assuming the necessary requirements are meant, the option turns green, and we can download the MARC file. 

I was experimenting with the local conversion, installed via git clone, on the same ruby application, and got successful conversion, as noted here in our conversion notes [spreadsheet](https://api.stage.sinopia.io/resource/1a4d25e0-aee9-40ed-b4c0-9bfc74c08340), the MARC data is printed to the terminal, but there does not seem to be any option for running that same script for producing a MARC file locally, and when I copied that data printed to the screen, which looked like MARC data, and included LEADER data, into a file and saved in a .mrk file, the attempt to compile into the binary .mrc file was unsuccessful because no LEADER data was included (an attempt to run the file in Marcedit against MARC validation rules produced significant error messaging about that data, starting with the LEADER. The .mrk file I is included [here](https://drive.google.com/file/d/1Ywy-q9Z0KirEmMKAq3GTVUfS15xg4L15/view?usp=sharing). So, there is some issue with the conversion that is not fulfilling something in the MARC standards it seems to me. Not sure exactly where though. 
My next step will be to look at the conversion internally to see if the same MARC file produced, and downloaded, also is having this validation issue I am seeing. 
thank you (PS: This was mentioned on slack, but I will delete that post and keep it here as an issue for tracking purposes.
thank you much

**Comment by jyssy** [comment]
Quick followup: It looks like a run of the same [Instance](https://api.stage.sinopia.io/resource/1a4d25e0-aee9-40ed-b4c0-9bfc74c08340) conversion, when run internally, DOES produce a more clearly defined binary file withmore indicators and the (=0 that re required in Marcedit, as seen here: 
![image](https://user-images.githubusercontent.com/30397506/101929542-9d9a3c80-3b9c-11eb-9610-606172c069e2.png) The record is not perfect, so I think the external conversion option will need to have the same specs and output. Curious to see where this will go. Thank you

**Comment by justinlittman** [comment]
Hey @jyssy --  Just want to make sure I understand. You'd like to request binary file export from the commandline tool (i.e., external conversion); you're not reporting a bug.

**Comment by jyssy** [comment]
(sorry for my delay here) Well, basically, yes. part of the testing is to test the validity of the output - which means that I think we will need that generation of a MARC record to be used externally as well (at this point, via the CLI). The data that is printed to the terminal, which I have copied into a file, is NOT validating and requires a ton of edits that the built-in converter does not need. Is that helpful? thank you Justin
