### ISSUE TITLE
Testing EXT converter and the generated MARC record

### ISSUE THREAD

**Issue by jyssy** [LD4P/rdf2marc#42]
I tested converting this [Instance](https://api.stage.sinopia.io/resource/728fc24c-184b-425d-afed-7cd99a536213), and, after updating ruby and the bundle, ran the converter from the CLI. 
I have 2 comments with 2 questions.

1. The resultant MARC record is produced, but even though the above Instance contains a 'Main Title' the 245 is NOT being generated, either to the terminal or in the MARC file. Why might this be? Because the 245 is not being generated, the record is technically not valid, but the data is there in the Instance I think... (let me know if I should be doing something differently) 
2.  Thank you so much for adding the external production of the MARC file with the simplicity of running the same single command. But I am curious if there is some way of automatically producing a file that is marked in either .mrk or .mrc (preferred). This may not be possible, or is too complex, but I do at least want to ask. Otherwise, this is moving in the right direction. thank you again

**Comment by justinlittman** [comment]
Can you say more about what you mean by "marked in either .mrk or .mrc (preferred)"?

**Comment by justinlittman** [comment]
Re: 1. The converter is not expecting title to be a list.

**Comment by jyssy** [comment]
Sure, just wondering if the file that is produced could be a .mrc record instead of a .mar extension (if that is something that could be controlled). Re: your response to 1., are you saying that the converter is not expecting anything for 245? Or am I misunderstanding your question? :smile:

**Comment by justinlittman** [comment]
In your profile, the title is specified as order. This produces different RDF that the converter isn't expecting.

![image](https://user-images.githubusercontent.com/588335/106896692-eca5af00-66bf-11eb-9669-d7269d1ce11c.png)

**Comment by jyssy** [comment]
@justinlittman I am editing this now. Curious, what exactly does 'ordered' do to the RDF? How does it change it? Obviously, I thought it meant something different than it does. thank you

**Comment by jyssy** [comment]
So, I edited the Instance RT, got rid of the 'ordered' and made a new instance, here, [https://api.stage.sinopia.io/resource/e8b1efe5-a5cf-4b71-a551-715f29f92dca](url) but I have run into the same issue, no 245 is being produced. What think ye? thank you

**Comment by justinlittman** [comment]
It is still a list. I wonder if the profile was cached in Sinopia. Try a hard refresh and then opening the instance.

**Comment by justinlittman** [comment]
RDF has no notion of ordering. Thus, if, for example, you say an instance has two titles, the ordering of those titles have no implied order and may come back from the RDF parser in any order. However, there are several conventions (which vary based on the serialization) for specifying order.

This is one of the things that make RDF very difficult to write applications for. It would be significant additional work to have the converter handle ordered OR unordered lists. (Unlike, say, JSON, where ordered lists comes for free.)

**Comment by jyssy** [comment]
When I open the [Instance](https://api.stage.sinopia.io/resource/UChicago:RT:bf2:Monograph:Instance), I find that 'ordered' has been removed, but this is what I saw and was testing with this next instance of an 'Instance' :smile: What do yo mean by hard reset? I have logged out and back in, etc. **thank you** (Not sure if the cache to which you are referring is on the browser side of server side).

**Comment by justinlittman** [comment]
Browser refresh. On my Mac, this is splat+shift+r.

**Comment by jyssy** [comment]
Thank you (Chrome on linux has a couple different hard refresh options), but I am seeing that this [Instance](https://api.stage.sinopia.io/resource/e8b1efe5-a5cf-4b71-a551-715f29f92dca) is opening with unused triples now. This was the new Instance I created, I think, based upon my edited Instance RT (sans 'ordered') So, this was unexpected.

**Comment by michelleif** [comment]
i tried previewing and opening the above instance and there were no unused triples. @jyssy can we close this ticket?

**Comment by michelleif** [comment]
I'm closing this ticket and if there are still problems please open a new ticket.
