### ISSUE TITLE
Error running the ruby CLI script

### ISSUE THREAD

**Issue by jyssy** [LD4P/rdf2marc#45]
Good morning

I attempted to convert this [Instance](https://api.stage.sinopia.io/resource/fbc43365-0b3a-4e29-b41b-6b1e4bf643a3), which is one of the central PCC templates (for Monograph Instance) but I received this error: 

`W, [2021-04-15T10:33:04.812886 #51220]  WARN -- : Resolving http://vocab.getty.edu/aat/300060417 to Rdf2marc::Models::SubjectAccessField::GenreForm not supported.
Traceback (most recent call last):
	6: from exe/rdf2marc:16:in `<main>'
	5: from /home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/converter.rb:15:in `convert'
	4: from /home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/rdf2model.rb:9:in `to_model'
	3: from /home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/rdf2model/mapper.rb:18:in `generate'
	2: from /home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/rdf2model/mappers/subject_access_fields.rb:19:in `generate'
	1: from /home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/rdf2model/mappers/subject_access_fields.rb:19:in `each'
/home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/rdf2model/mappers/subject_access_fields.rb:25:in `block in generate': **undefined method `value' for #<RDF::Node:0x697a8(_:b11)> (NoMethodError)
Did you mean?  evaluate**`

I am not sure if data is missing or if this is a bug. That error of 'undefined method' makes me think it is a bug, but it could be missing data. But I think I have all the required data entered. No rush, but wanted to look at this conversion of contributors for our meeting next week. thank you

**Comment by justinlittman** [comment]
`http://vocab.getty.edu/aat` URIs are not supported. Currently, only resolving `id.loc.gov` URIs are supported.

**Comment by jyssy** [comment]
thank you, ok. thank you

**Comment by jyssy** [comment]
Curious, how long does it take for any reindexing? I made the change and ran the script, with the same error. No rush. thank you

**Comment by justinlittman** [comment]
Zero latency. What is the commandline that you executed?

**Comment by jyssy** [comment]
exe/rdf2marc and the same Instance [URI](https://api.stage.sinopia.io/resource/fbc43365-0b3a-4e29-b41b-6b1e4bf643a3).

**Comment by justinlittman** [comment]
When I execute, this is returning a different error because the subject is a list:
```
"http://id.loc.gov/ontologies/bibframe/subject": [
        {
          "@list": [
            {
              "@id": "http://id.loc.gov/authorities/names/n79046200"
            },
            {
              "@id": "http://id.loc.gov/authorities/subjects/sh85026379"
            }
          ]
        }
      ]
```

rdf2marc does not currently handle subjects as lists.

**Comment by jyssy** [comment]
Ok, so you are saying that there can only be one subject for a resource? Or is that an issue with the template, you think? If in the template, I will reach out to someone about the template.  Thank you Justin.

**Comment by jyssy** [comment]
Hm, I attempted to convert this [URI](https://api.stage.sinopia.io/resource/39089327-a05d-4184-b7c0-aaf5f018748d), that was built this morning with the UChicago template, I got the same error. 

"Traceback (most recent call last):
	7: from exe/rdf2marc:16:in `<main>'
	6: from /home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/converter.rb:15:in `convert'
	5: from /home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/rdf2model.rb:9:in `to_model'
	4: from /home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/rdf2model/mapper.rb:18:in `generate'
	3: from /home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/rdf2model/mappers/subject_access_fields.rb:16:in `generate'
	2: from /home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/rdf2model/mappers/subject_access_fields.rb:55:in `genre_forms'
	1: from /home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/rdf2model/mappers/subject_access_fields.rb:55:in `map'
/home/jal359/Documents/GitHub/rdf2marc/lib/rdf2marc/rdf2model/mappers/subject_access_fields.rb:62:in `block in genre_forms': **undefined method `value' for #<RDF::Node:0x69794(_:b10)> (NoMethodError)
Did you mean?  evaluate** "

Now, I am not sure what the issue is. I checked to see if my ruby was out of date, but it is current.

**Comment by jyssy** [comment]
I also attempted to convert the PCC template-created one with the INTERNAL converter, but that was NOT successful (maybe for the same reason you mentioned). / Also, I attempted to convert the UChicago-created MDS - which was also not successful. So, I am getting failures on both of these URI Instances in both INT and EXT conversion situations.

**Comment by justinlittman** [comment]
Form of work is modeled differently in `UChicago:RT:bf2:Monograph:Work` than (expected) `pcc:bf2:Monograph:Work`.

**Comment by justinlittman** [comment]
There can be multiple subjects; they just can't be ordered, which is specified in the template.

**Comment by michelleif** [comment]
looking at UChicago:RT:bf2:Monograph:Work on stage today, there are no ordered properties, something else must be causing error. @justinlittman can you assist?

**Comment by justinlittman** [comment]
For `UChicago:RT:bf2:Monograph:Work`, form of work is a nested `ld4p:RT:bf2:Form`. For `pcc:bf2:Monograph:Work`, it is a lookup. This results in different RDF.

**Comment by jyssy** [comment]
Ok, I will certainly make the change to the UChicago RT, but I still am having the same issue mentioned above with the PCC template.

**Comment by jyssy** [comment]
Also, update, when I made that change to the UChicago template, used that as the Work for the PCC Instance template, the conversion also worked fine in INT and EXT conversion tools. I think we can close this issue for now, thank you @justinlittman
