### ISSUE TITLE
First indicator for 650 field incorrect

### ISSUE THREAD

**Issue by NancyL** [LD4P/rdf2marc#53]
**Type of change**
change to existing mapping/ defect?

**Example RDF records**
https://api.stage.sinopia.io/resource/1f9f50e0-5316-466a-affc-4bc3c51e89d3

**Resource template**
Which resource template does this apply to? In which Sinopia environment (development, stage, production)?
ld4p:RT:bf2:Monograph:Work:Un-nested (Stage)

**Expected MARC**
What MARC did you expect to receive?
650 _0 $a Gamache, Armand (Fictitious character) $0 http://id.loc.gov/authorities/subjects/sh2007009191 (_meaning "blank")

**Actual MARC**
What MARC did you actually receive (if mapped incorrectly)?
650 00 $a Gamache, Armand (Fictitious character) $0 http://id.loc.gov/authorities/subjects/sh2007009191 

**Expected mapping logic**
bf:subject with a value with URI beginning http://id.loc.gov/authorities/subjects/[...]
maps to 650 _0

**Comment by jcoyne** [comment]
https://api.stage.sinopia.io/resource/1f9f50e0-5316-466a-affc-4bc3c51e89d3 is a BF:Work, but we need a BF:Instance to run rdf2marc. https://api.stage.sinopia.io/resource/d7e62aba-e269-4609-87d3-0139c5c098cd is the BF:Instance.

**Comment by NancyL** [comment]
This is now correct!
