### ISSUE TITLE
100 field is not being converted

### ISSUE THREAD

**Issue by NancyL** [LD4P/rdf2marc#54]
**Type of change**
Change to existing mapping

**Example RDF records**
https://api.stage.sinopia.io/resource/1f9f50e0-5316-466a-affc-4bc3c51e89d3

_:b1 a <http://id.loc.gov/ontologies/bflc/PrimaryContribution>;
    <http://id.loc.gov/ontologies/bibframe/agent> <http://id.loc.gov/authorities/names/n2006006905>;
    <http://id.loc.gov/ontologies/bibframe/role> <http://id.loc.gov/vocabulary/relators/aut>.
<http://id.loc.gov/authorities/names/n2006006905> a <http://id.loc.gov/ontologies/bibframe/Person>;
    <http://www.w3.org/2000/01/rdf-schema#label> "Penny, Louise@en".
<http://id.loc.gov/vocabulary/relators/aut> <http://www.w3.org/2000/01/rdf-schema#label> "Author".

**Resource template**
Stage: ld4p:RT:bf2:Monograph:Work:Un-nested (_Monograph Work (BF2) Un-Nested)

**Expected MARC**
100 1# $a Penny, Louise
245 10 $a All the devils are here $c Louise Penny

**Actual MARC**
245 10 $a All the devils are here $c Louise Penny

**Note: This worked before. I think the addition of the resource attribute "suppressible" in the template has broken it**

**Expected mapping logic**
bflc:Primary Contribution -- bf:agent <a URI> -- type: a bf:Person -- rdfs:label "string". 
1. Create a 100 field with first indicator "1" (110 2# if a bf:Organization; 111 2# if a bf:Conference)
2. Look up URI?
3. Take label from lookup and add after $a in MARC record
4. Add the URI in a $0

Now I see this is also a problem with the 700 field.

**Comment by jcoyne** [comment]
https://api.stage.sinopia.io/resource/1f9f50e0-5316-466a-affc-4bc3c51e89d3 is a BF:Work, but we need a BF:Instance to run rdf2marc

**Comment by NancyL** [comment]
This is now working correctly!
