### ISSUE TITLE
Add roles given in bf:Contribution

### ISSUE THREAD

**Issue by NancyL** [LD4P/rdf2marc#55]
**Type of change**
New mapping

**Example RDF records**
https://api.stage.sinopia.io/resource/6e95e390-e677-4bb3-b438-0065d83e4d53

_:b3 a <http://id.loc.gov/ontologies/bflc/PrimaryContribution>;
    <http://id.loc.gov/ontologies/bibframe/agent> <http://id.loc.gov/authorities/names/nb2004311516>;
    <http://id.loc.gov/ontologies/bibframe/role> <http://id.loc.gov/vocabulary/relators/aut>.
<http://id.loc.gov/authorities/names/nb2004311516> a <http://id.loc.gov/ontologies/bibframe/Person>;
    <http://www.w3.org/2000/01/rdf-schema#label> "Laws, John Muir@en".
<http://id.loc.gov/vocabulary/relators/aut> <http://www.w3.org/2000/01/rdf-schema#label> "Author".
_:b4 a <http://id.loc.gov/ontologies/bibframe/Contribution>;
    <http://id.loc.gov/ontologies/bibframe/agent> <http://id.loc.gov/authorities/names/nb2004311516>;
    <http://id.loc.gov/ontologies/bibframe/role> <http://id.loc.gov/vocabulary/relators/ill>.
<http://id.loc.gov/vocabulary/relators/ill> <http://www.w3.org/2000/01/rdf-schema#label> "Illustrator".

**Resource template**
Stage: ld4p:RT:bf2:Monograph:Work:Un-nested (_Monograph Work (BF2) Un-Nested)

**Expected MARC**
What MARC did you expect to receive?

245 10 $a The Laws guide to nature drawing and journaling / $c written and illustrated by John Muir Laws.

**Actual MARC**
100 1# $a Laws, John Muir, $e author $4 http://id.loc.gov/vocabulary/relators/aut
245 10 $a The Laws guide to nature drawing and journaling / $c written and illustrated by John Muir Laws.
700 1# $a Laws, John Muir, $e illustrator $4 http://id.loc.gov/vocabulary/relators/ill

The issue of the missing 100 & 700 field is addressed in issue 11.

**Expected mapping logic**
bf:role <URI> ; rdfs:label "label" becomes:
100/700 1# $a etc. "name label", $e "rdfs:label" $4 <URI>
Note there is a comma after the name label followed by a space: $a Name, $e

BLOCKED BY ISSUE #54

**Comment by justinlittman** [comment]
Note that these should be lookups rather than using the label in the RDF.

**Comment by jcoyne** [comment]
@NancyL is there a sample instance record we can use? It looks like you linked to a Work, but we can only run rdf2marc on an instance record.

**Comment by NancyL** [comment]
I tried to create a new record covering this last night (the other one, which did have an attached instance has been deleted) but stage wasn't indexing. I'll try again.

**Comment by NancyL** [comment]
Try https://api.stage.sinopia.io/resource/5142ffee-7f93-4e85-8337-8515b13d2e36

**Comment by NancyL** [comment]
and another: https://api.stage.sinopia.io/resource/3eb5f480-60d6-4732-8daf-02d8d6f26eb7

**Comment by ndushay** [comment]
Another way to describe this ticket is "Add relator terms to subfield e for 1xx and 7xx fields"

**Comment by justinlittman** [comment]
@NancyL The fix for this was tricky. Can you please test in DEVELOPMENT?

**Comment by NancyL** [comment]
On my one test, it seems to work well (even if I put in a 2nd role with the same contributor). People may not like that it is capitalized, but there is nothing we can do about that.

**Comment by NancyL** [comment]
This is working in stage as well as development
