### ISSUE TITLE
OCLC record number put into incorrect field

### ISSUE THREAD

**Issue by NancyL** [LD4P/rdf2marc#56]
**Type of change**
Change/finessing of an existing mapping

**Example RDF records**
https://api.stage.sinopia.io/resource/ce068a4e-8d86-4f84-9693-3dc5fabc5280

<http://id.loc.gov/ontologies/bibframe/identifiedBy> _:b20, _:b21, _:b22;
...
_:b22 a <http://id.loc.gov/ontologies/bibframe/Local>;
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "1141759043"@eng;
    <http://id.loc.gov/ontologies/bibframe/source> _:b23.
_:b23 a <http://id.loc.gov/ontologies/bibframe/Source>;
    <http://www.w3.org/2000/01/rdf-schema#label> "OCoLC"@eng.

**Resource template**
STAGE: ld4p:RT:bf2:Monograph:Instance:Un-nested (_Monograph Instance (BF2) Un-Nested)

**Expected MARC**
035 ## $a (OCoLC)1141759043

**Actual MARC**
001 ## 1141759043

**Expected mapping logic**
For bf:identifier a bf:Local ;
   rdf:value "string of numbers"
   bf:source [a bf:Source ;
        rdfs:label "OCoLC" ]
1. create an 035, both indicators blank
2. Input: $a Label from bf:Source in parentheses (OCoLC), followed by (with no space after closing parens)
3. "string of numbers"

**Comment by jcoyne** [comment]
Are there any circumstances where we should continue to map to the 001 field?

**Comment by justinlittman** [comment]
@NancyL ?

**Comment by vitustang** [comment]
Question: Are there any circumstances where we should continue to map to the 001 field?

Answer: No, not when the "source" of the identifier is OCoLC, e.g.
:b23 a http://id.loc.gov/ontologies/bibframe/Source;
http://www.w3.org/2000/01/rdf-schema#label "OCoLC"@eng.

**Comment by jcoyne** [comment]
@vitustang what about when the source is not OCoLC?

**Comment by justinlittman** [comment]
Have we determined where to put the ckey? Because if not, we wouldn't expect to find it as a local identifier.
