### ISSUE TITLE
Map a 245 second indicator value in conversion

### ISSUE THREAD

**Issue by NancyL** [LD4P/rdf2marc#57]
New mapping.
https://api.stage.sinopia.io/resource/ca44ec67-a40c-4486-a6f1-d70b58cb3775

_:b1 a <http://id.loc.gov/ontologies/bibframe/Title>;
    <http://id.loc.gov/ontologies/bibframe/mainTitle> "The Laws guide to nature drawing and journaling"@eng.

**Resource template**
stage pcc:bf2:Title:InstanceTitle (Title--Instance Title)
stage ld4p:RT:bf2:InstanceTitle (Instance title)

245 14 The Laws guide to nature drawing and journaling

**Actual MARC**
What MARC did you actually receive (if mapped incorrectly)?

245 10 The Laws guide to nature drawing and journaling

**Expected mapping logic**
The second indicator gives the number of non-filing characters, i.e., how many characters to skip when indexing a title. The characters generally are articles such as "The", "An", "Ein", "La", etc. The count includes the space after the word. A number is used so that it works in multiple languages rather than giving a list of stop words.

One possibility is to create a new Sinopia property used with bf:Title:
bf:Title [ a bf:Title ;
   sinopia:nonfilingCount "4" ;
   bf:mainTitle "The Laws guide to nature drawing and journaling" ; 
   etc.
This number would be entered by the cataloger.

When converting to MARC the rule would be:
For sinopia:nonfilingCount value, enter the value in the 245 second indicator.

There may well be other ways to do this as well. This is what I could come up with for now. It would be worth asking LC how they do it (the person I asked did not know)

**Comment by justinlittman** [comment]
@NancyL Is there anything that can be done for this mapping? Or can this ticket be closed?

**Comment by NancyL** [comment]
I don't know what you are asking here.

**Comment by NancyL** [comment]
The second indicator of the 245 is supposed to indicate the number of non-filing characters--something a cataloger puts in manually--so that indexing skips words such as "The", "Ein", etc. and the space that follows before the next word. That is the only way MARC has figured out how to do this in a multi-language/multi-script environment. It is not correct MARC if that indicator is not correct.

I was hoping we could enhance Sinopia with a local property to put in the non-filing number, which is potentially useful in LD discovery environments, and could be dropped into the MARC 245 second indicator on rdf2marc conversion. But I think I see now my idea wouldn't work (it would have needed some Sinopia enhancement as well) unless there was a way to internally associate it only with the one field--bf:mainTitle in the bf:Instance.

So I guess I should have put this in Sinopia enhancement requests rather than here first.

**Comment by michelleif** [comment]
@NancyL can you follow up with LC to see how they are getting the # of nonfiling characters from BF?

**Comment by NancyL** [comment]
So they have bflc:titleSortKey which picks up the title based on non-filing characters, but this is only when converting from MARC to BF. It remains unchanged after that no matter what you do to the title.

[to remain unnamed here] "has proposed using Unicode non-sorting markers, which are permissible in the MARC communications format (https://www.loc.gov/marc/specifications/specchargeneral.html#basechar):

non-sorting character(s) begin, 88(hex) in MARC-8 and 98(hex) in Unicode encoding
non-sorting character(s) end, 89(hex) in MARC-8 and 9C(hex) in Unicode encoding
I don’t think it’s a good idea since the characters are not ASCII and would be hidden (invisible?) in the editor."

This would not be visible to the cataloger, so certainly not ideal, and unlikely, I think, to be implemented. And I'm not sure if they are meaning to add that to the BF or in the MARC...

**Comment by NancyL** [comment]
I've been speaking with Nate, though he won't get back to me with an answer till this coming week. We may have a possible (and fairly simple) solution

**Comment by NancyL** [comment]
Since LC is still waffling on what to do about non-filing indicators, I would propose that we create one using a Sinopia property that could potentially be converted at some point to a more universal one. The property could be fairly simple: sinopia:nonfilingIndicator with an integer as its value. That value would then be mapped into the MARC 245 field, as the value for the second indicator. That would be (for us) its only use, though the Europeans might use it in other fields. If we do not do this, catalogers will need to enter it manually into the MARC record.

In the new edition of the specs, LC is doing a sparql query that differentiates between the length of the bf:mainTitle or bf:Title (if bf:mainTitle not present) and the bflc:titleSortKey. (query below). I get how they do this in MARC2BF conversion, but not BF2MARC. I have asked but have not yet received an answer.
if (bflc:titleSortKey &&
  rdfs:label &&
  bflc:titleSortKey.length < rdfs:label.length) {
  rdfs:label.length - bflc:titleSortKey.length
} else {
  "0"
}

**Comment by justinlittman** [comment]
@NancyL How about `http://sinopia.io/vocabulary/bf/nonfiling`?

**Comment by NancyL** [comment]
sounds good to me!

**Comment by justinlittman** [comment]
https://github.com/LD4P/sinopia_editor/pull/3570 adds it to the vocab.

![image](https://user-images.githubusercontent.com/588335/181002961-047d467e-5b92-4868-af16-b7635e77085e.png)

Let me know when it has been added to a template and there is an example record. (No need to wait for the vocab PR to be deployed before beginning to use the URI.)

**Comment by NancyL** [comment]
I have one in stage but I'm guessing you need the example in dev?

**Comment by justinlittman** [comment]
```
exe/rdf2marc https://api.development.sinopia.io/resource/74ee9129-332b-4291-b167-50cec6f8838f
LEADER      nam a22     uu 4500
008 220726s2021    nyu                 eng||
040    $a CSt $b eng $c CSt $e rda
100 1  $a Cogman, Genevieve $e Author $0 http://id.loc.gov/authorities/names/no2015010106
245 14 $a The untold story $b an Invisible Library novel $c Genevieve Cogman
250    $a First edition
264  1 $a New York (N.Y.) $b Ace Books $c 2021
300    $a 284 pages $c 21 cm
336    $a Text $b text $0 https://id.loc.gov/vocabulary/contentTypes/text $2 rdacontent
337    $a unmediated $b n $0 https://id.loc.gov/vocabulary/mediaTypes/n $2 rdamedia
338    $a volume $b nc $0 http://id.loc.gov/vocabulary/carriers/nc $2 rdacarrier
490 0  $a Invisible Library novel / Genevieve Cogman
500    $a Transcribed publication statement: New York : Ace, 2021
650  0 $a Fiction $0 http://id.loc.gov/authorities/subjects/sh85048050
650  7 $a Librarians $2 fast $0 http://id.worldcat.org/fast/997301
650  7 $a Libraries $2 fast $0 http://id.worldcat.org/fast/997341
655  7 $a Fantasy fiction $0 http://id.loc.gov/authorities/genreForms/gf2014026333 $2 lcgft
758    $4 http://id.loc.gov/ontologies/bibframe/instanceOf $i Instance of: $a Untold story $0 https://api.development.sinopia.io/resource/53eefac7-984f-4cf8-951b-04565b4c6642
884    $a Sinopia rdf2marc $g 20220727 $k https://api.development.sinopia.io/resource/74ee9129-332b-4291-b167-50cec6f8838f $u https://github.com/LD4P/rdf2marc
```

**Comment by NancyL** [comment]
looks good! Very exciting!
