### ISSUE TITLE
Automate deployment

### ISSUE THREAD

**Issue by justinlittman** [LD4P/rdf2marc#61]
Preferably similar to other Sinopia projects but with the added complication that this is a Lambda.

**Comment by justinlittman** [comment]
See these instructions for creating lambda zip: https://github.com/LD4P/rdf2marc/tree/master/lambda-s3

**Comment by ndushay** [comment]
In working on adding code coverage, I'm comparing with dlme-transform.  You are probably already aware of the need for some env variables in circleci:  https://app.circleci.com/settings/project/github/sul-dlss/dlme-transform/environment-variables?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fgithub%2Fsul-dlss%2Fdlme-transform
